### ISSUE TITLE
![Screenshot_20240703_091404_Tonkeeper](https://github.com/tonkeeper/wallet-api/assets/174173485/27e52557-b536-41e7-9520-83d882553ed9)

### ISSUE THREAD

**Issue by Hedar779** [tonkeeper/links#104]
![Screenshot_20240703_091404_Tonkeeper](https://github.com/tonkeeper/wallet-api/assets/174173485/27e52557-b536-41e7-9520-83d882553ed9)
seed24 I forgot the tonkeeper number

_Originally posted by @Mmmm17m in https://github.com/tonkeeper/wallet-api/issues/33#issuecomment-2205145499_

**Comment by Sophiestanworth** [comment]
If you forgot the tonkeeper number for seed24, you might want to try reaching out to them directly to get the info you need. I'll have to refer you to the official support live chat with the ticket ID TON07638
Please see the link below to our dedicated support line:
[Tonkeeper Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by Sophiestanworth** [comment]
If you forgot the tonkeeper number for seed24, you might want to try reaching out to them directly to get the info you need. I'll have to refer you to the official support live chat with the ticket ID TON07638
Please see the link below to our dedicated support line:
[Tonkeeper Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
@Hedar779

**Comment by Annawoody** [comment]
If you forgot the tonkeeper number for seed24, you might want to try reaching out to them directly to get the info you need. I'll have to refer you to the official support live chat with the ticket ID TON07638
Please see the link below to our dedicated support line:
[Tonkeeper Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
@Hedar779

**Comment by Hamid13630210** [comment]
> ```
>           ![Screenshot_20240703_091404_Tonkeeper](https://github.com/tonkeeper/wallet-api/assets/174173485/27e52557-b536-41e7-9520-83d882553ed9)
> ```
> 
> seed24 شماره تونکیپر را فراموش کردم
> 
> _در اصل توسط@Mmmm17mدر [شماره 33 (نظر)](https://github.com/tonkeeper/wallet-api/pull/33#issuecomment-2205145499)_
